---
language: java
jdk:
  - openjdk8
group: edge 
services:
  - redis-server
sources:
  - sourceline: 'deb https://packages.chef.io/repos/apt/stable focal main'
env:
  - GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json
before_install:
  - redis-server --daemonize yes
install:
  - echo $GOOGLE_APPLICATION_CREDENTIALS_B64 | base64 --decode >> $HOME/credentials.json
  - curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.1.0/ktlint && chmod a+x ktlint
  - sudo snap install --classic kotlin
cache:
  - directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.konan/cache
script:
  - ./ktlint "**/*.kt"
  - chmod +x pubsub/gradlew
  - chmod +x symlink_check.sh; ./symlink_check.sh 
  - nproc
  - free -hm
  - kotlinc -help
  - kotlinc -X
  - kotlinc -version
  - |
    for DIR in ./*/; do
      if [ -f $DIR/gradlew ]; then
        pushd $DIR
        ./gradlew test --console=plain --info
        popd
      fi
    done
