language: java
jdk:
  - oraclejdk8
env:
  - GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json
install:
  - echo $GOOGLE_APPLICATION_CREDENTIALS_B64 | base64 --decode >> $HOME/credentials.json
  - curl -sSLO https://github.com/shyiko/ktlint/releases/download/0.24.0/ktlint && chmod a+x ktlint
script:
  - ./ktlint "**/*.kt"
  - |
    set -e
    for DIR in ./*/; do
      if [ -f $DIR/gradlew ]; then
        pushd $DIR
        ./gradlew test --console=plain --info
        popd
      fi
    done
